"""empty message

Revision ID: 4fdb069c75c5
Revises: 7b6c5888d06b
Create Date: 2020-05-23 23:55:28.736372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdb069c75c5'
down_revision = '7b6c5888d06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('food', 'carbohydrates',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('food', 'fat',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('food', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('food', 'protein',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'protein',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('food', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('food', 'fat',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('food', 'carbohydrates',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('food', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
